"""Initial migration

Revision ID: 58d7c47cf96c
Revises: 
Create Date: 2026-08-16 13:49:42.332461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d7c47cf96c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('departments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('departments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'departments', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_column('departments', 'created_at')
    op.drop_column('departments', 'description')
    op.drop_column('departments', 'code')
    # ### end Alembic commands ###
